title: Dev Speedwagon Media Works
baseurl: ""
css_path: "/assets/css/main.css" # CSS para desarrollo

include:
  - assets/sass
  - assets/scss
  - node_modules/bootstrap/scss/
  
collections:
  autores:
    autor: true
    output: true      
  sellos:
    sello: true
    output: true   
  libros:
    libro: true
    output: true 

collections_dir: my_collections